server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cb8738oxfvy6.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929?allowMultiQueries=true
    username: lee4339
    password: 1q2w3e4r

  security:
    user:
      name: admin
      password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:\programing\Junil\Geonho\springboot\stussy-clone-20220929/upload/
