server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cb8738oxfvy6.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929?allowMultiQueries=true
    username: lee4339
    password: 1q2w3e4r

  security:
    user:
      name: admin
      password: 1q2w3e4r
    oauth2:
      client:
        registration:
          google:
            clientId: 1035857168756-2pnthjdomt99upe9213ve26e5k5irhar.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            clientId: HzOukJNuo4aG0NOyVfnh
            clientSecret: AAoQPIecaR
            scope:
              - email
              - name
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:\programing\Junil\Geonho\springboot\stussy-clone-20220929/upload/
